AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys OpenGovernance Platform to AWS Organization
Parameters:
  IAMUsernameInOrganizationAccount:
    Type: String
    Default: OpenGovernanceIAMUser
    Description: IAM User to create
  IAMGroupnameInOrganizationAccount:
    Type: String
    Default: OpenGovernanceIAMGroup
    Description: IAM User to create
  RoleNameInAccount:
    Type: String
    Default: OpenGovernanceReadOnly
    Description: The name of the role that will be assumed in each member account.
  AccountList:
    Type: String
    Default: ""
    Description: List of Accounts to deploy the stackset to.
  OrganizationUnitList:
    Type: String
    Default: ""
    Description: List of OUs to deploy the stackset to.

Conditions:
  OUs: !Not [ !Equals [ !Ref OrganizationUnitList, ''] ]
  Accounts: !Not [ !Equals [ !Ref AccountList, ''] ]

Resources:
  OrganizationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref RoleNameInAccount
      Description: Allows the platform to gather inventory of the organization and member accounts
      Policies:
        - PolicyName: OpenGovernanceRoleAssumption
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'organizations:List*'
                  - 'sts:AssumeRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${AWS::AccountId}' 
            Action:
              - 'sts:AssumeRole'
              - 'sts:TagSession'
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/SecurityAudit
          - arn:aws:iam::aws:policy/ReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSSSODirectoryReadOnly
          - arn:aws:iam::aws:policy/AWSSSOReadOnly
          - arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly
          - arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess
  IAMUserInOrganizationAccount:
   Type: 'AWS::IAM::User'
   Properties:
    UserName: !Ref IAMUsernameInOrganizationAccount
  IAMGroupInOrganizationAccount:
   Type: 'AWS::IAM::Group'
   Properties:
     GroupName: !Ref IAMGroupnameInOrganizationAccount
  AddOrganizationUserToOrganizationGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
     Users:
      - !Ref IAMUserInOrganizationAccount
     GroupName: !Ref IAMGroupInOrganizationAccount
  AttachRoleToOrganizationGroup:
      Type: 'AWS::IAM::GroupPolicy'
      Properties:
        PolicyName: OpenGovernanceAllowRoleAssumption
        GroupName: !Ref IAMGroupInOrganizationAccount
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 'sts:AssumeRole'
              Resource: !GetAtt OrganizationRole.Arn
  MemberAccountRoleStackSet:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      StackSetName: OpenGovernanceMemberAccountRollout
      Description: Stack Set that will roll out to member account
      Capabilities:
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      PermissionModel: SERVICE_MANAGED
      OperationPreferences:
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        MaxConcurrentCount: 15
        FailureTolerancePercentage: 100
      StackInstancesGroup:
        - DeploymentTargets: 
            Accounts: !If [Accounts, !Split [ ",", !Ref AccountList ], !Ref AWS::NoValue]
            OrganizationalUnitIds: !If [OUs, !Split [ ",", !Ref OrganizationUnitList ], !Ref  AWS::NoValue]
          Regions: 
            - !Ref AWS::Region
      ManagedExecution:
        Active: true
      Parameters: 
        - ParameterKey: OrganizationRoleArn
          ParameterValue: !GetAtt OrganizationRole.Arn  
        - ParameterKey: MemberAccountRoleName
          ParameterValue: !Ref RoleNameInAccount
      TemplateBody: |
        {
          "AWSTemplateFormatVersion": "2010-09-09",
          "Description": "Create a reader role in member accounts.",
          "Parameters": {
              "OrganizationRoleArn": {
                  "Type": "String",
                  "Description": "The role that is allowed to assume the role."
              },
              "MemberAccountRoleName": {
                  "Type": "String",
                  "Description": "The name of the role that will be deployed in each member account."
              }
          },
          "Resources": {
              "OpenGovernance": {
                  "Type": "AWS::IAM::ManagedPolicy",
                  "Properties": {
                      "ManagedPolicyName": "OpenGovernancePolicy",
                      "Description": "A Limited policy to allow cloudquery to do its job",
                      "PolicyDocument": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Deny",
                                  "Resource": "*",
                                  "Action": [
                                      "cloudformation:GetTemplate",
                                      "dynamodb:GetItem",
                                      "dynamodb:BatchGetItem",
                                      "dynamodb:Query",
                                      "dynamodb:Scan",
                                      "ec2:GetConsoleOutput",
                                      "ec2:GetConsoleScreenshot",
                                      "ecr:BatchGetImage",
                                      "ecr:GetAuthorizationToken",
                                      "ecr:GetDownloadUrlForLayer",
                                      "kinesis:Get*",
                                      "lambda:GetFunction",
                                      "logs:GetLogEvents",
                                      "s3:GetObject",
                                      "sdb:Select*",
                                      "sqs:ReceiveMessage"
                                  ]
                              }
                          ]
                      }
                  }
              },
              "MemberAccountReadOnlyRole": {
                  "Type": "AWS::IAM::Role",
                  "Properties": {
                      "RoleName": { "Ref" : "MemberAccountRoleName" },
                      "Description": "Read Only Access for to fetch inventory from member accounts",
                      "ManagedPolicyArns": [
                          {
                              "Ref": "OpenGovernance"
                          },
                          "arn:aws:iam::aws:policy/ReadOnlyAccess",
                          "arn:aws:iam::aws:policy/SecurityAudit",
                          "arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess",
                          "arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess",
                          "arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess",
                          "arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly"
                      ],
                      "MaxSessionDuration": 28800,
                      "AssumeRolePolicyDocument": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "AWS": {
                                          "Fn::Sub": "${OrganizationRoleArn}"
                                      }
                                  },
                                  "Action": [
                                      "sts:AssumeRole",
                                      "sts:TagSession"
                                        ]
                                    }
                                ]
                            }
                        }
                    }
                }
        }


Outputs:
  CFNOrganizationRoleArn:
    Description: Organization Role.
    Value: !GetAtt OrganizationRole.Arn
  AccessKeyId:
    Description: Name of the IAM User
    Value: !Ref IAMUsernameInOrganizationAccount
    